# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'buildConfigUi.ui'
#
# Created: Fri Aug 22 19:57:28 2014
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_buildConfig(object):
    def setupUi(self, buildConfig):
        buildConfig.setObjectName(_fromUtf8("buildConfig"))
        buildConfig.resize(457, 354)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../pic/dapeng.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        buildConfig.setWindowIcon(icon)
        self.horizontalLayoutWidget = QtGui.QWidget(buildConfig)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(80, 60, 291, 51))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.privateHLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.privateHLayout.setMargin(0)
        self.privateHLayout.setObjectName(_fromUtf8("privateHLayout"))
        self.privateCheckBox = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.privateCheckBox.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("../pic/private.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.privateCheckBox.setIcon(icon1)
        self.privateCheckBox.setIconSize(QtCore.QSize(28, 28))
        self.privateCheckBox.setShortcut(_fromUtf8(""))
        self.privateCheckBox.setObjectName(_fromUtf8("privateCheckBox"))
        self.privateHLayout.addWidget(self.privateCheckBox)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.privateHLayout.addItem(spacerItem)
        self.tokenButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.tokenButton.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("../pic/token.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tokenButton.setIcon(icon2)
        self.tokenButton.setIconSize(QtCore.QSize(28, 28))
        self.tokenButton.setFlat(True)
        self.tokenButton.setObjectName(_fromUtf8("tokenButton"))
        self.privateHLayout.addWidget(self.tokenButton)
        self.tokenLineEdit = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.tokenLineEdit.setObjectName(_fromUtf8("tokenLineEdit"))
        self.privateHLayout.addWidget(self.tokenLineEdit)
        self.line1 = QtGui.QFrame(buildConfig)
        self.line1.setGeometry(QtCore.QRect(0, 110, 471, 16))
        self.line1.setFrameShape(QtGui.QFrame.HLine)
        self.line1.setFrameShadow(QtGui.QFrame.Sunken)
        self.line1.setObjectName(_fromUtf8("line1"))
        self.ideLabel = QtGui.QLabel(buildConfig)
        self.ideLabel.setGeometry(QtCore.QRect(80, 260, 91, 16))
        self.ideLabel.setObjectName(_fromUtf8("ideLabel"))
        self.line = QtGui.QFrame(buildConfig)
        self.line.setGeometry(QtCore.QRect(-10, 250, 481, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.suiteLabel = QtGui.QLabel(buildConfig)
        self.suiteLabel.setGeometry(QtCore.QRect(70, 120, 61, 16))
        self.suiteLabel.setObjectName(_fromUtf8("suiteLabel"))
        self.testsuiteTreeWidget = QtGui.QTreeWidget(buildConfig)
        self.testsuiteTreeWidget.setGeometry(QtCore.QRect(90, 140, 151, 101))
        self.testsuiteTreeWidget.setTextElideMode(QtCore.Qt.ElideLeft)
        self.testsuiteTreeWidget.setObjectName(_fromUtf8("testsuiteTreeWidget"))
        self.testsuiteTreeWidget.header().setVisible(False)
        self.verticalLayoutWidget_4 = QtGui.QWidget(buildConfig)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(260, 140, 101, 101))
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.testSuiteAddButton = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.testSuiteAddButton.setObjectName(_fromUtf8("testSuiteAddButton"))
        self.verticalLayout.addWidget(self.testSuiteAddButton)
        self.testSuiteRemoveButton = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.testSuiteRemoveButton.setObjectName(_fromUtf8("testSuiteRemoveButton"))
        self.verticalLayout.addWidget(self.testSuiteRemoveButton)
        self.testSuiteComboBox = QtGui.QComboBox(self.verticalLayoutWidget_4)
        self.testSuiteComboBox.setObjectName(_fromUtf8("testSuiteComboBox"))
        self.verticalLayout.addWidget(self.testSuiteComboBox)
        self.stackedWidget = QtGui.QStackedWidget(buildConfig)
        self.stackedWidget.setGeometry(QtCore.QRect(110, 290, 331, 41))
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.iarPage = QtGui.QWidget()
        self.iarPage.setObjectName(_fromUtf8("iarPage"))
        self.iarButton = QtGui.QPushButton(self.iarPage)
        self.iarButton.setGeometry(QtCore.QRect(0, 10, 41, 21))
        self.iarButton.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("../pic/iar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.iarButton.setIcon(icon3)
        self.iarButton.setIconSize(QtCore.QSize(26, 26))
        self.iarButton.setAutoDefault(False)
        self.iarButton.setDefault(False)
        self.iarButton.setFlat(True)
        self.iarButton.setObjectName(_fromUtf8("iarButton"))
        self.iarLineEdit = QtGui.QLineEdit(self.iarPage)
        self.iarLineEdit.setGeometry(QtCore.QRect(40, 10, 209, 20))
        self.iarLineEdit.setObjectName(_fromUtf8("iarLineEdit"))
        self.iarComboBox = QtGui.QComboBox(self.iarPage)
        self.iarComboBox.setGeometry(QtCore.QRect(250, 10, 75, 20))
        self.iarComboBox.setObjectName(_fromUtf8("iarComboBox"))
        self.stackedWidget.addWidget(self.iarPage)
        self.uv4Page = QtGui.QWidget()
        self.uv4Page.setObjectName(_fromUtf8("uv4Page"))
        self.uv4Button = QtGui.QPushButton(self.uv4Page)
        self.uv4Button.setGeometry(QtCore.QRect(0, 10, 41, 20))
        self.uv4Button.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("../pic/uv4.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uv4Button.setIcon(icon4)
        self.uv4Button.setIconSize(QtCore.QSize(20, 20))
        self.uv4Button.setFlat(True)
        self.uv4Button.setObjectName(_fromUtf8("uv4Button"))
        self.uv4LineEdit = QtGui.QLineEdit(self.uv4Page)
        self.uv4LineEdit.setGeometry(QtCore.QRect(40, 10, 209, 20))
        self.uv4LineEdit.setObjectName(_fromUtf8("uv4LineEdit"))
        self.uv4ComboBox = QtGui.QComboBox(self.uv4Page)
        self.uv4ComboBox.setGeometry(QtCore.QRect(250, 10, 75, 20))
        self.uv4ComboBox.setObjectName(_fromUtf8("uv4ComboBox"))
        self.stackedWidget.addWidget(self.uv4Page)
        self.gccPage = QtGui.QWidget()
        self.gccPage.setObjectName(_fromUtf8("gccPage"))
        self.gccButton = QtGui.QPushButton(self.gccPage)
        self.gccButton.setGeometry(QtCore.QRect(0, 10, 31, 21))
        self.gccButton.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("../pic/gcc.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gccButton.setIcon(icon5)
        self.gccButton.setIconSize(QtCore.QSize(25, 25))
        self.gccButton.setFlat(True)
        self.gccButton.setObjectName(_fromUtf8("gccButton"))
        self.gccLineEdit = QtGui.QLineEdit(self.gccPage)
        self.gccLineEdit.setGeometry(QtCore.QRect(40, 10, 209, 20))
        self.gccLineEdit.setObjectName(_fromUtf8("gccLineEdit"))
        self.gccOpenButton = QtGui.QPushButton(self.gccPage)
        self.gccOpenButton.setGeometry(QtCore.QRect(250, 10, 71, 21))
        self.gccOpenButton.setObjectName(_fromUtf8("gccOpenButton"))
        self.stackedWidget.addWidget(self.gccPage)
        self.kdsPage = QtGui.QWidget()
        self.kdsPage.setObjectName(_fromUtf8("kdsPage"))
        self.kdsButton = QtGui.QPushButton(self.kdsPage)
        self.kdsButton.setGeometry(QtCore.QRect(0, 10, 41, 21))
        self.kdsButton.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("../pic/kds.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.kdsButton.setIcon(icon6)
        self.kdsButton.setIconSize(QtCore.QSize(25, 25))
        self.kdsButton.setFlat(True)
        self.kdsButton.setObjectName(_fromUtf8("kdsButton"))
        self.kdsLineEdit = QtGui.QLineEdit(self.kdsPage)
        self.kdsLineEdit.setGeometry(QtCore.QRect(40, 10, 209, 20))
        self.kdsLineEdit.setObjectName(_fromUtf8("kdsLineEdit"))
        self.kdsOpenButton = QtGui.QPushButton(self.kdsPage)
        self.kdsOpenButton.setGeometry(QtCore.QRect(250, 10, 71, 21))
        self.kdsOpenButton.setObjectName(_fromUtf8("kdsOpenButton"))
        self.stackedWidget.addWidget(self.kdsPage)
        self.cwPage = QtGui.QWidget()
        self.cwPage.setObjectName(_fromUtf8("cwPage"))
        self.cw10Button = QtGui.QPushButton(self.cwPage)
        self.cw10Button.setGeometry(QtCore.QRect(0, 10, 41, 21))
        self.cw10Button.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("../pic/codewarrior.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cw10Button.setIcon(icon7)
        self.cw10Button.setIconSize(QtCore.QSize(25, 25))
        self.cw10Button.setFlat(True)
        self.cw10Button.setObjectName(_fromUtf8("cw10Button"))
        self.cw10LineEdit = QtGui.QLineEdit(self.cwPage)
        self.cw10LineEdit.setGeometry(QtCore.QRect(40, 10, 209, 20))
        self.cw10LineEdit.setObjectName(_fromUtf8("cw10LineEdit"))
        self.cw10OpenButton = QtGui.QPushButton(self.cwPage)
        self.cw10OpenButton.setGeometry(QtCore.QRect(250, 10, 71, 21))
        self.cw10OpenButton.setObjectName(_fromUtf8("cw10OpenButton"))
        self.stackedWidget.addWidget(self.cwPage)
        self.mingwPage = QtGui.QWidget()
        self.mingwPage.setObjectName(_fromUtf8("mingwPage"))
        self.mingwButton = QtGui.QPushButton(self.mingwPage)
        self.mingwButton.setGeometry(QtCore.QRect(0, 10, 41, 21))
        self.mingwButton.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("../pic/mingw.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mingwButton.setIcon(icon8)
        self.mingwButton.setIconSize(QtCore.QSize(25, 25))
        self.mingwButton.setFlat(True)
        self.mingwButton.setObjectName(_fromUtf8("mingwButton"))
        self.mingwLlineEdit = QtGui.QLineEdit(self.mingwPage)
        self.mingwLlineEdit.setGeometry(QtCore.QRect(40, 10, 209, 20))
        self.mingwLlineEdit.setObjectName(_fromUtf8("mingwLlineEdit"))
        self.mingwOpenButton = QtGui.QPushButton(self.mingwPage)
        self.mingwOpenButton.setGeometry(QtCore.QRect(250, 10, 71, 21))
        self.mingwOpenButton.setObjectName(_fromUtf8("mingwOpenButton"))
        self.stackedWidget.addWidget(self.mingwPage)
        self.ideComboBox = QtGui.QComboBox(buildConfig)
        self.ideComboBox.setGeometry(QtCore.QRect(20, 300, 71, 22))
        self.ideComboBox.setObjectName(_fromUtf8("ideComboBox"))

        self.retranslateUi(buildConfig)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(buildConfig)
        buildConfig.setTabOrder(self.privateCheckBox, self.tokenButton)
        buildConfig.setTabOrder(self.tokenButton, self.tokenLineEdit)

    def retranslateUi(self, buildConfig):
        buildConfig.setWindowTitle(_translate("buildConfig", "Build Configuration", None))
        buildConfig.setStatusTip(_translate("buildConfig", "GUI of Build Station Configuration", None))
        buildConfig.setWhatsThis(_translate("buildConfig", "<html><head/><body><p><br/></p></body></html>", None))
        self.privateCheckBox.setStatusTip(_translate("buildConfig", "If you want configurate a private station, checked the box", None))
        self.tokenButton.setStatusTip(_translate("buildConfig", "If the station is private, please set a token", None))
        self.tokenLineEdit.setStatusTip(_translate("buildConfig", "If the station is private, please set a token", None))
        self.ideLabel.setStatusTip(_translate("buildConfig", "Configurate the IDEs that needed", None))
        self.ideLabel.setText(_translate("buildConfig", "<html><head/><body><p align=\"center\">IDE Configuration</p></body></html>", None))
        self.suiteLabel.setStatusTip(_translate("buildConfig", "Select the test suites that you need", None))
        self.suiteLabel.setText(_translate("buildConfig", "<html><head/><body><p align=\"center\">Test Suites</p></body></html>", None))
        self.testsuiteTreeWidget.setStatusTip(_translate("buildConfig", "Test Suite you have selected", None))
        self.testsuiteTreeWidget.headerItem().setText(0, _translate("buildConfig", "Test Suite", None))
        self.testSuiteAddButton.setStatusTip(_translate("buildConfig", "Add the test suites you have selected", None))
        self.testSuiteAddButton.setText(_translate("buildConfig", "Add", None))
        self.testSuiteRemoveButton.setStatusTip(_translate("buildConfig", "Remove the test suite you have selected", None))
        self.testSuiteRemoveButton.setText(_translate("buildConfig", "Remove", None))
        self.testSuiteComboBox.setStatusTip(_translate("buildConfig", "Select test suite you need", None))
        self.iarButton.setStatusTip(_translate("buildConfig", "Configurate your IAR path", None))
        self.iarLineEdit.setStatusTip(_translate("buildConfig", "Configurate your IAR path", None))
        self.iarComboBox.setStatusTip(_translate("buildConfig", "Select the lastest version of IAR", None))
        self.uv4Button.setStatusTip(_translate("buildConfig", "Configurate your UV4 path", None))
        self.uv4LineEdit.setStatusTip(_translate("buildConfig", "Configurate your UV4 path", None))
        self.uv4ComboBox.setStatusTip(_translate("buildConfig", "Select the lastest version of UV4", None))
        self.gccButton.setStatusTip(_translate("buildConfig", "Configurate your GCC path", None))
        self.gccLineEdit.setStatusTip(_translate("buildConfig", "Configurate your GCC path", None))
        self.gccOpenButton.setStatusTip(_translate("buildConfig", "Configurate your GCC path", None))
        self.gccOpenButton.setText(_translate("buildConfig", "Open", None))
        self.kdsButton.setStatusTip(_translate("buildConfig", "Configurate your KDS path", None))
        self.kdsLineEdit.setStatusTip(_translate("buildConfig", "Configurate your KDS path", None))
        self.kdsOpenButton.setStatusTip(_translate("buildConfig", "Configurate your KDS path", None))
        self.kdsOpenButton.setText(_translate("buildConfig", "Open", None))
        self.cw10Button.setStatusTip(_translate("buildConfig", "Configurate your Code Worrior path", None))
        self.cw10LineEdit.setStatusTip(_translate("buildConfig", "Configurate your Code Worrior path", None))
        self.cw10OpenButton.setStatusTip(_translate("buildConfig", "Configurate your Code Worrior path", None))
        self.cw10OpenButton.setText(_translate("buildConfig", "Open", None))
        self.mingwButton.setStatusTip(_translate("buildConfig", "MinGW is required when use gcc_arm (e.g. C:/MinGW)", None))
        self.mingwLlineEdit.setStatusTip(_translate("buildConfig", "Configurate your MinGW path", None))
        self.mingwOpenButton.setStatusTip(_translate("buildConfig", "Configurate your MinGW path", None))
        self.mingwOpenButton.setText(_translate("buildConfig", "Open", None))
        self.ideComboBox.setStatusTip(_translate("buildConfig", "Select your IDE", None))

