# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'runConfigUi.ui'
#
# Created: Sun Aug 17 18:00:30 2014
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_runConfig(object):
    def setupUi(self, runConfig):
        runConfig.setObjectName(_fromUtf8("runConfig"))
        runConfig.setWindowModality(QtCore.Qt.WindowModal)
        runConfig.resize(550, 498)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../pic/dapeng.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        runConfig.setWindowIcon(icon)
        runConfig.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.horizontalLayoutWidget = QtGui.QWidget(runConfig)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(70, 60, 291, 51))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.privateHLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.privateHLayout.setMargin(0)
        self.privateHLayout.setObjectName(_fromUtf8("privateHLayout"))
        self.privateCheckBox = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.privateCheckBox.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("../pic/private.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.privateCheckBox.setIcon(icon1)
        self.privateCheckBox.setIconSize(QtCore.QSize(28, 28))
        self.privateCheckBox.setShortcut(_fromUtf8(""))
        self.privateCheckBox.setObjectName(_fromUtf8("privateCheckBox"))
        self.privateHLayout.addWidget(self.privateCheckBox)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.privateHLayout.addItem(spacerItem)
        self.tokenButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.tokenButton.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("../pic/token.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tokenButton.setIcon(icon2)
        self.tokenButton.setIconSize(QtCore.QSize(28, 28))
        self.tokenButton.setFlat(True)
        self.tokenButton.setObjectName(_fromUtf8("tokenButton"))
        self.privateHLayout.addWidget(self.tokenButton)
        self.tokenLineEdit = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.tokenLineEdit.setObjectName(_fromUtf8("tokenLineEdit"))
        self.privateHLayout.addWidget(self.tokenLineEdit)
        self.debuggerListWidget = QtGui.QListWidget(runConfig)
        self.debuggerListWidget.setGeometry(QtCore.QRect(0, 120, 91, 121))
        self.debuggerListWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.debuggerListWidget.setFlow(QtGui.QListView.TopToBottom)
        self.debuggerListWidget.setObjectName(_fromUtf8("debuggerListWidget"))
        item = QtGui.QListWidgetItem()
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("../pic/jlink.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon3)
        self.debuggerListWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("../pic/trace32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon4)
        self.debuggerListWidget.addItem(item)
        self.debuggerStackedWidget = QtGui.QStackedWidget(runConfig)
        self.debuggerStackedWidget.setGeometry(QtCore.QRect(90, 120, 451, 361))
        self.debuggerStackedWidget.setFrameShape(QtGui.QFrame.Box)
        self.debuggerStackedWidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.debuggerStackedWidget.setObjectName(_fromUtf8("debuggerStackedWidget"))
        self.jlinkPage = QtGui.QWidget()
        self.jlinkPage.setObjectName(_fromUtf8("jlinkPage"))
        self.jlinkButton = QtGui.QPushButton(self.jlinkPage)
        self.jlinkButton.setGeometry(QtCore.QRect(10, 20, 41, 21))
        self.jlinkButton.setIconSize(QtCore.QSize(40, 32))
        self.jlinkButton.setFlat(True)
        self.jlinkButton.setObjectName(_fromUtf8("jlinkButton"))
        self.jlinkOpenButton = QtGui.QPushButton(self.jlinkPage)
        self.jlinkOpenButton.setGeometry(QtCore.QRect(240, 20, 75, 23))
        self.jlinkOpenButton.setObjectName(_fromUtf8("jlinkOpenButton"))
        self.jlinkLineEdit = QtGui.QLineEdit(self.jlinkPage)
        self.jlinkLineEdit.setGeometry(QtCore.QRect(50, 20, 181, 20))
        self.jlinkLineEdit.setObjectName(_fromUtf8("jlinkLineEdit"))
        self.jlinkPlatformButton = QtGui.QPushButton(self.jlinkPage)
        self.jlinkPlatformButton.setGeometry(QtCore.QRect(10, 40, 101, 51))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("../pic/platform.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.jlinkPlatformButton.setIcon(icon5)
        self.jlinkPlatformButton.setIconSize(QtCore.QSize(40, 40))
        self.jlinkPlatformButton.setFlat(True)
        self.jlinkPlatformButton.setObjectName(_fromUtf8("jlinkPlatformButton"))
        self.treeWidget = QtGui.QTreeWidget(self.jlinkPage)
        self.treeWidget.setGeometry(QtCore.QRect(0, 110, 411, 251))
        self.treeWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        self.debuggerStackedWidget.addWidget(self.jlinkPage)
        self.lauterbachPage = QtGui.QWidget()
        self.lauterbachPage.setObjectName(_fromUtf8("lauterbachPage"))
        self.lauterbachPlatformButton = QtGui.QPushButton(self.lauterbachPage)
        self.lauterbachPlatformButton.setGeometry(QtCore.QRect(20, 70, 101, 51))
        self.lauterbachPlatformButton.setIcon(icon5)
        self.lauterbachPlatformButton.setIconSize(QtCore.QSize(40, 40))
        self.lauterbachPlatformButton.setFlat(True)
        self.lauterbachPlatformButton.setObjectName(_fromUtf8("lauterbachPlatformButton"))
        self.trace32LineEdit = QtGui.QLineEdit(self.lauterbachPage)
        self.trace32LineEdit.setGeometry(QtCore.QRect(50, 20, 181, 20))
        self.trace32LineEdit.setObjectName(_fromUtf8("trace32LineEdit"))
        self.trace32OpenButton = QtGui.QPushButton(self.lauterbachPage)
        self.trace32OpenButton.setGeometry(QtCore.QRect(240, 20, 75, 23))
        self.trace32OpenButton.setObjectName(_fromUtf8("trace32OpenButton"))
        self.trace32Button = QtGui.QPushButton(self.lauterbachPage)
        self.trace32Button.setGeometry(QtCore.QRect(0, 20, 51, 21))
        self.trace32Button.setIconSize(QtCore.QSize(32, 32))
        self.trace32Button.setFlat(True)
        self.trace32Button.setObjectName(_fromUtf8("trace32Button"))
        self.debuggerStackedWidget.addWidget(self.lauterbachPage)

        self.retranslateUi(runConfig)
        self.debuggerStackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(runConfig)
        runConfig.setTabOrder(self.privateCheckBox, self.tokenButton)
        runConfig.setTabOrder(self.tokenButton, self.tokenLineEdit)
        runConfig.setTabOrder(self.tokenLineEdit, self.jlinkPlatformButton)

    def retranslateUi(self, runConfig):
        runConfig.setWindowTitle(_translate("runConfig", "Run Configuration", None))
        runConfig.setStatusTip(_translate("runConfig", "GUI of Run Station Configuration", None))
        self.privateCheckBox.setStatusTip(_translate("runConfig", "If you want configurate a private station, checked the box", None))
        self.tokenButton.setStatusTip(_translate("runConfig", "If the station is private, please set a token", None))
        self.tokenLineEdit.setStatusTip(_translate("runConfig", "If the station is private, please set a token", None))
        self.debuggerListWidget.setStatusTip(_translate("runConfig", "Configurate of Debugger -- Jlink or Lauterbach", None))
        __sortingEnabled = self.debuggerListWidget.isSortingEnabled()
        self.debuggerListWidget.setSortingEnabled(False)
        item = self.debuggerListWidget.item(0)
        item.setText(_translate("runConfig", "Jlink", None))
        item = self.debuggerListWidget.item(1)
        item.setText(_translate("runConfig", "Lauterbach", None))
        self.debuggerListWidget.setSortingEnabled(__sortingEnabled)
        self.jlinkButton.setStatusTip(_translate("runConfig", "Jlink is required when use gdb(e.g. C:/SEGGER/JLinkARM_V480g)", None))
        self.jlinkButton.setText(_translate("runConfig", "Jlink", None))
        self.jlinkOpenButton.setStatusTip(_translate("runConfig", "Configurate your Jlink path", None))
        self.jlinkOpenButton.setText(_translate("runConfig", "Open", None))
        self.jlinkLineEdit.setStatusTip(_translate("runConfig", "Configurate your Jlink path", None))
        self.jlinkPlatformButton.setStatusTip(_translate("runConfig", "Select the platforms you need", None))
        self.jlinkPlatformButton.setText(_translate("runConfig", "Platform", None))
        self.treeWidget.headerItem().setText(0, _translate("runConfig", "Platform", None))
        self.treeWidget.headerItem().setText(1, _translate("runConfig", "Value", None))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("runConfig", "Platform", None))
        self.treeWidget.topLevelItem(1).setText(0, _translate("runConfig", "Device_Type", None))
        self.treeWidget.topLevelItem(2).setText(0, _translate("runConfig", "Serial_Port", None))
        self.treeWidget.topLevelItem(3).setText(0, _translate("runConfig", "Debug_Port", None))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.lauterbachPlatformButton.setStatusTip(_translate("runConfig", "Select the platforms you need", None))
        self.lauterbachPlatformButton.setText(_translate("runConfig", "Platform", None))
        self.trace32LineEdit.setStatusTip(_translate("runConfig", "Configurate your Trace32 path", None))
        self.trace32OpenButton.setStatusTip(_translate("runConfig", "Configurate your Trace32 path", None))
        self.trace32OpenButton.setText(_translate("runConfig", "Open", None))
        self.trace32Button.setStatusTip(_translate("runConfig", "Trace32 is required when use lauterbach(e.g. C:/T32)", None))
        self.trace32Button.setText(_translate("runConfig", "Trace32", None))

